"""squashed baseline (pre-production)

Revision ID: 0010
Revises:
Create Date: 2026-07-06

Squash of the former revisions 0001-0010. There were no production instances at
the time, so the incremental history was collapsed into this no-op baseline.

The revision id deliberately stays "0010" so existing dev databases (which are
stamped at the old head "0010") keep resolving. On a fresh database the schema
is built by `init_schema_and_migrations()` via `SQLModel.metadata.create_all`,
which then stamps head; `0010` itself is a no-op.

The 2.0 schema is frozen as of this baseline. From 2.0 on, every schema change
ships as a real, autogenerated Alembic revision stacked on top of `0010` —
autogenerate is wired (see `migrations/env.py`, `target_metadata =
SQLModel.metadata`). The pre-production "edit the models and recreate the DB"
workflow no longer applies.

Note for anyone upgrading a pre-2.0 development database: `create_all` does not
alter existing tables, so a DB carried over from before 2.0 (or stamped at a
pre-squash revision 0001-0009) must be recreated once — after that, migrations
carry it forward.
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
