"""add checklist.suggest_existing_items

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-18

Adds the per-card ``suggest_existing_items`` flag (default true). Controls the
client-side "suggest unchecking an existing checked item instead of creating a
duplicate" helper. Stacked on the 2.0 baseline ``0010`` per the post-2.0
"every schema change is a real autogenerated revision" workflow.

On a fresh database ``create_all`` builds the column from the model and head is
stamped, so this revision is a no-op there; on a dev DB carried across it adds
the column and back-fills existing rows to true via the server default.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "checklist",
        sa.Column(
            "suggest_existing_items",
            sa.Boolean(),
            nullable=True,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    op.drop_column("checklist", "suggest_existing_items")
