"""group shares: living membership

Revision ID: 0012
Revises: 0011
Create Date: 2026-07-19

Turns "share with a group" into a first-class, living share. Adds:

* ``checklist_group_share`` — the source-of-truth rows (checklist × OIDC group →
  permission) behind a group share, and
* ``checklist_collaborator.via_group`` — a nullable provenance marker: NULL means
  an explicit individual share (every pre-existing row), a group name means the
  collaborator row was materialized from that group share and is owned by the
  reconciler.

Stacked on the 2.0 baseline ``0010`` (via ``0011``) per the post-2.0 "every
schema change is a real autogenerated revision" workflow.

Back-compat on an existing (productive) database: members shared via the old
one-shot group expansion already exist as plain ``checklist_collaborator`` rows;
after this migration they carry ``via_group = NULL`` and are therefore treated as
**explicit** shares — they keep access exactly as before. They are simply not yet
governed by a ``checklist_group_share`` record, so re-sharing that group makes
their access "living" going forward. Non-destructive.

On a fresh database ``create_all`` builds both objects from the models and head is
stamped, so this revision is a no-op there; on a carried-over DB it creates the
table and adds the column.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: Union[str, None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "checklist_group_share",
        sa.Column("checklist_id", sa.Uuid(), nullable=False),
        sa.Column("group", sa.String(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("server_seq", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["checklist_id"], ["checklist.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("checklist_id", "group"),
    )
    op.create_index(
        op.f("ix_checklist_group_share_server_seq"),
        "checklist_group_share",
        ["server_seq"],
        unique=False,
    )
    op.add_column(
        "checklist_collaborator",
        sa.Column("via_group", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("checklist_collaborator", "via_group")
    op.drop_index(
        op.f("ix_checklist_group_share_server_seq"),
        table_name="checklist_group_share",
    )
    op.drop_table("checklist_group_share")
